[window]
padding.x = 18
padding.y = 18
decorations = "Full"
opacity = 0.85
title = "Terminal"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 13.0

[font.normal]
family = "M PLUS CODE Latin"
style = "Regular"

[font.bold]
family = "M PLUS CODE Latin"
style = "Bold"

[font.italic]
family = "M PLUS CODE Latin"
style = "Italic"

# Kanagawa Dragon Alacritty Colors

[colors.primary]
background = '#181616'
foreground = '#E8DCC4'

[colors.normal]
black = '#0d0c0c'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#c8c093'

[colors.bright]
black = '#a6a69c'
red = '#e46876'
green = '#87a987'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#c5c9c5'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#b98d7b'


[cursor.style]
shape = "Block"
blinking = "On"

[cursor]
blink_interval = 750

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"
