# Font
font_family      CaskaydiaMono Nerd Font 
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0

# Sane Defaults
cursor_shape beam
detect_urls yes
remember_window_size  yes
confirm_os_window_close 0


background_opacity 0.85

enable_audio_bell no
visual_bell_duration 0.0


# base16-default-dark colors for kitty
# https://github.com/tinted-theming/base16-emacs

background              #181818
foreground              #d8d8d8
selection_background    #383838
selection_foreground    #d8d8d8

cursor                  #d8d8d8
cursor_text_color       #181818

url_color               #7cafc2

color0  #181818 
color1  #ab4642 
color2  #a1b56c 
color3  #f7ca88 
color4  #7cafc2 
color5  #ba8baf  
color6  #86c1b9   
color7  #d8d8d8 

# ── Bright colors (8–15) 
color8  #585858   
color9  #ab4642  
color10 #a1b56c 
color11 #f7ca88 
color12 #7cafc2 
color13 #ba8baf 
color14 #86c1b9 
color15 #f8f8f8 
