backend = "glx";
vsync = true;

active-opacity = 1.0;

# Default opacity of inactive windows.
inactive-opacity = 1.0;

# Opacity of window titlebars and borders.
frame-opacity = 1.0;

# Application-specific settings; these override the default `active-opacity`
opacity-rule = [
    "90:class_g = 'kitty'"
];


shadow = true;
shadow-radius = 12;
shadow-opacity = 0.15;
shadow-offset-x = -8;
shadow-offset-y = -8;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 8;
